### ISSUE TITLE
TypeError: Can't convert 'Tag' object to str implicitly

### ISSUE THREAD

**Issue by M157q** [M157q/zdict#17]
$ zdict pan
Traceback (most recent call last):
  File "/Users/m157q/.virtualenvs/zdict/bin/zdict", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/m157q/GitHub/zdict/scripts/zdict", line 5, in <module>
    main()
  File "/Users/m157q/GitHub/zdict/zdict/zdict.py", line 293, in main
    ydict.lookup(w)
  File "/Users/m157q/GitHub/zdict/zdict/dictionaries.py", line 52, in lookup
    record = self.query(word)
  File "/Users/m157q/GitHub/zdict/zdict/plugins/yahoo_dict.py", line 132, in query
    sentence += word
TypeError: Can't convert 'Tag' object to str implicitly

**Comment by M157q** [comment]
![screen shot 2015-06-26 at 7 28 56 am](https://cloud.githubusercontent.com/assets/1645228/8367825/0ef007b8-1bd5-11e5-9959-0fb9b22a8c75.png)
The reason is that result on the webpage is broken...
